name: Update data
on:
  schedule:
    - cron: '0 19 * * * '
jobs:
  update:
    name: update data
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: python setup
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: python install
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
      - name: run script
        run: |
          echo ::set-output name=results::$(python scripts/update.py)
        id: run_script
      - name: commit
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: steps.run_script.outputs.results == 'update' 
        run: |
          git config --global user.email "covid19-bot@example.com"
          git config --global user.name "covid19-bot"
          git add -A
          git status
          git commit -m "[ci] update"
          git push -q "https://$GH_TOKEN@github.com/mauforonda/arrestos-cuarentena.git" master
          
        
        
